# https://github.com/Kernel-Nomad/vuzon
services:
  vuzon:
    container_name: vuzon
    image: ghcr.io/kernel-nomad/vuzon:latest
    env_file:
      - .env
    environment:
      PORT: "8001"
    restart: unless-stopped
    ports:
      - "${VUZON_PORT:-8001}:8001"
